server:
  port: 8081

spring:
  security:
    oauth2:
      client:
        registration:
          keycloak:
            client-id: demo-client
            authorization-grant-type: authorization_code
            scope: openid,email,profile
        provider:
          keycloak:
            user-name-attribute: preferred_username
            authorization-uri: "http://keycloak.local/realms/myrealm/protocol/openid-connect/auth"
            token-uri: "http://keycloak:8080/realms/myrealm/protocol/openid-connect/token"
            user-info-uri: "http://keycloak:8080/realms/myrealm/protocol/openid-connect/userinfo"
            jwk-set-uri: "http://keycloak:8080/realms/myrealm/protocol/openid-connect/certs"
  session:
    store-type: redis
  data:
    redis:
      host: redis
      port: 6379

logging:
  level:
    org.springframework.security: TRACE
    org.keycloak=DEBUG: DEBUG