apiVersion: v1
kind: Service
metadata:
  name: java-app-1
spec:
  selector:
    app: java-app
    replica-id: "1"
  ports:
    - protocol: TCP
      port: {{ .Values.service.port }}
      targetPort: 8081
